version: '3'
services:
  main:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=main-main-1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=duygusen
      - ME_CONFIG_BASICAUTH_PASSWORD=test
    depends_on:
      - main-main-1

networks:
  my-network:
    driver: bridge